---
- name: Avi SE | CSP | Image deploy | See if the qcow image already exists
  uri:
    url: "https://{{ inventory_hostname }}/api/operational/repository/image/{{ se_csp_qcow_image_name }}/_operations/get_image"
    method: POST
    user: "{{ se_csp_user }}"
    password: "{{ se_csp_password }}"
    force_basic_auth: yes
    headers:
      Accept: '*/*'
    validate_certs: false
    return_content: true
  failed_when: false
  register: se_image_exists
  delegate_to: localhost

- block:
    - set_fact:
        se_image_exists_json: "{{ se_image_exists.content|from_json }}"
    - debug: msg="Image {{ se_image_exists_json.output.name }} already exists."
  when: se_image_exists.status == 200

- block:
    - name: Avi SE | CSP | Image deploy | Verify qcow exists locally
      stat:
        path: "{{ se_csp_qcow_image_file }}"
      delegate_to: localhost
      register: se_qcow_status
      failed_when: not se_qcow_status.stat.exists
    - name: Avi SE | CSP | Image deploy | SCP qcow to csp device
      shell: sshpass -p {{ se_csp_password }} scp -o StrictHostKeyChecking=no {{ se_csp_qcow_image_file }} {{ se_csp_user }}@{{ inventory_hostname }}:/osp/repository
      delegate_to: localhost
      failed_when: false
  when: se_image_exists.status != 200
